export const arrayFotos = [
    {   
        id:1,
        url:'https://picsum.photos/400/100'
    },
    {   
        id:2,
        url:'https://picsum.photos/400/200'
    },
    {   
        id:3,
        url:'https://picsum.photos/400/300'
    },
    {   
        id:4,
        url:'https://picsum.photos/400/400'
    },
    {   
        id:5,
        url:'https://picsum.photos/400/500'
    },
    {   
        id:6,
        url:'https://picsum.photos/400/400'
    },
    {   
        id:7,
        url:'https://picsum.photos/400/500'
    },
    {   
        id:8,
        url:'https://picsum.photos/400/400'
    },
    {   
        id:9,
        url:'https://picsum.photos/400/500'
    },
    {   
        id:10,
        url:'https://picsum.photos/400/400'
    },
    {   
        id:11,
        url:'https://picsum.photos/400/500'
    },
    {   
        id:12,
        url:'https://picsum.photos/400/500'
    }
]